use_frameworks!

platform :ios, '9.0'

target 'LPHFoundation_Example' do
  pod 'LPHFoundation', :path => '../'

  target 'LPHFoundation_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
